dustpath/models/__init__.py
from flask_mongoengine import MongoEngine
from .users import User, AuthSecret 
from .maps import CircleMap

db = MongoEngine()

__all__ = [
    User, CircleMap
]


def init_db(app):
    db.init_app(app)
    
def init_mongoengine(settings):
    import mongoengine as me

    dbname = settings.get("MONGODB_DB")
    host = settings.get("MONGODB_HOST", "localhost")
    port = int(settings.get("MONGODB_PORT", "27017"))
    username = settings.get("MONGODB_USERNAME", "")
    password = settings.get("MONGODB_PASSWORD", "")
    me.connect(db=dbname, host=host, port=port, username=username, password=password)

dustpath/models/maps.py
import mongoengine as me
import datetime

class CircleMap(me.Document):
    meta = {'collection': 'circle_maps'}

    center = me.GeoPointField(required=True)
    radius = me.IntField(required=True)

dustpath/models/users.py
import mongoengine as me
import datetime
from flask_login import UserMixin

class AuthSecret(me.Document):
    meta = {'collection': 'auth_secrets'}
    user = me.ReferenceField('User', dbref=True, required=True)
    secret = me.StringField(required=True)
    create_at = me.DateTimeField(
            required=True,
            default=datetime.datetime.now)
    expire_at = me.DateTimeField(
            required=True,
            default=datetime.datetime.now() + datetime.timedelta(days=1))

class User(me.Document, UserMixin):
    meta = {'collection': 'users'}

    firstname = me.StringField(required=True)
    lastname = me.StringField(required=True)

dustpath/forms/__init__.py
from .user import ProfileForm

__all__ = [
    ProfileForm, 
]

dustpath/forms/user.py
from flask_wtf import FlaskForm
from wtforms import fields
# from wtforms.fields import html5
from wtforms import validators

class ProfileForm(FlaskForm):
    firstname = fields.StringField('ชื่อ',
                                 validators=[validators.Length(min=1)])
    lastname = fields.StringField('นามสกุล',
                                validators=[validators.Length(min=1)])

dustpath/__init__.py
__version__ = "0.0.1"

from flask import Flask


from . import models
from . import views


def create_app():
    app = Flask(__name__)
    app.config.from_object("dustpath.default_settings")
    app.config.from_envvar("DUSTPATH_SETTINGS", silent=True)

    models.init_db(app)
    views.register_blueprint(app)

    return app

dustpath/views/__init__.py
import datetime

from . import (
    index,
    users,
    maps,
    )


def add_date_url(url):
    now = datetime.datetime.now()
    return f'{url}?date={now.strftime("%Y%m%d")}'


def get_subblueprints(views=[]):
    blueprints = []
    for view in views:
        blueprints.append(view.module)

        if "subviews" in dir(view):
            for module in get_subblueprints(view.subviews):
                if view.module.url_prefix and module.url_prefix:
                    module.url_prefix = view.module.url_prefix + module.url_prefix
                blueprints.append(module)

    return blueprints


def register_blueprint(app):
    app.add_template_filter(add_date_url)
    blueprints = get_subblueprints(
        [
            index,
            users,
            maps,
        ])

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

dustpath/views/compile.py
from flask import (Blueprint,
                   Flask,
                   redirect,
                   render_template,
                   url_for,
                   current_app,
                   redirect)
from .. import models
import datetime
import mongoengine as me
import pathlib

module = Blueprint('main', __name__, url_prefix='/')

@module.route('/compile')
def compile_index():
    return render_template('compile/index.html)

dustpath/views/index.py
from flask import (Blueprint,
                   Flask,
                   redirect,
                   render_template,
                   url_for,
                   current_app,
                   redirect)
from .. import models
import datetime
import mongoengine as me
import pathlib

module = Blueprint('main', __name__, url_prefix='/')

@module.route('/')
def index():
    return render_template('main/index.html')

dustpath/views/maps.py
from flask import (Blueprint,
                   render_template,
                   redirect,
                   url_for,
                   request,
                   jsonify
                   )
import json, datetime
from flask_login import login_required
from .. import models

module = Blueprint('maps', __name__, url_prefix='/maps')

@module.route('/')
def index():
    maps = models.CircleMap.objects()
    return render_template('maps/index.html',
                            maps=maps,)

@module.route('/record', methods=['GET', 'POST'])
def record():
    
    center = [7.0065949668769205, 100.49891880632555] # lat, long
    zoom = 10
    
    if request.method == 'POST':
        data = request.json
        if data:
            circle_map = models.CircleMap(center=data['center'], radius=data['radius'])
            circle_map.save()
    return render_template('maps/record.html',
                           zoom=zoom,
                           center=center,)

dustpath/views/users.py
from flask import (Blueprint, render_template,
                   url_for, redirect, request)
from flask_login import (login_required)
from dustpath import models
from dustpath.forms import ProfileForm

module = Blueprint('users', __name__, url_prefix='/users')

@module.route('/record', methods=['GET', 'POST'])
def all_profile():
    user = models.User.objects().first()
    return render_template('users/profile.html', user=user)

@module.route('/record', methods=['GET', 'POST'])
def record():
    user_id = request.args.get('user_id')
    if user_id:
        user = models.User.objects.get(id=user_id)
        form = ProfileForm(obj=user)
    else:
        user = models.User()
        form = ProfileForm()
        
    if not form.validate_on_submit():
        return render_template('users/record.html', user=user,
                                                    form=form,)
    
    form.populate_obj(user)
    user.save()

    return redirect(url_for('users.record', user=user))

dustpath/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" media="all"
    href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url }}">

  <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url }}"></script>
  <script
    src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url }}"></script>

  <link rel="stylesheet" type="text/css" media="all"
    href="{{ url_for('static', filename='css/main.css') | add_date_url }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') | add_date_url }}">
  <link rel="icon" href="{{ url_for('static', filename='images/icon.png') }}">
  {% block additional_head %}{% endblock %}

  <title>{% block title %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
</head>

<body>
  {% block body %}{% endblock body %}

  <footer style="width: 100%; left: 0; bottom: 0; position: relative;">
    {% block footer %}
    {% include "base/footer.html" %}
    {% endblock footer %}
  </footer>
</body>

<script>
  $('.ui.dropdown')
    .dropdown();
  $(document)
    .ready(function () {
      $('.left.sidebar.menu')
        .sidebar('attach events', '.launch.icon.item', 'show')
        ;
    })
    ;
</script>

<style type="text/css">
  #link:hover {
    text-decoration: underline;
  }
</style>

{% block additional_js %}{% endblock %}

</html>

dustpath/templates/base/base-map.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        #mapid { 
            height: 60rem;
            background-color:white;
        }
        #back_btt{
            position: absolute; 
            margin: 9px;
            padding: 10px;
            width: 80px; 
            background-color: #ffffff; 
            border-radius: 10%;
            font-size: 30px; 
            text-align: center; 
            z-index: 10;
          }
    </style>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') }}">
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.css') }}" />
    <script src="{{ url_for('static', filename='node_modules/leaflet-draw/dist/leaflet.draw.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet-geometryutil/src/leaflet.geometryutil.js') }}"></script>
</head>

<body onload="brython()">
    {% block body %}{% endblock %}
</body>
</html>

dustpath/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block body %}

<div class="ui vertical inverted sidebar">
  {% include "base/navbar.html" %}
</div>

<div class="ui fixed main menu">
  <a class="launch icon item">
    <i class="content icon"></i>
  </a>
  <div class="item">
    <a id="link" href="/" style="color: black;">
      Dustpath
    </a>
  </div>
</div>

<div class="pusher" style="min-height: 84% !important;">
  <main class="twelve wide column" style="padding-top: 3em;">
    {% block content %}{% endblock content %}
  </main>
</div>

<script>
  var dropdown = document.getElementsByClassName("ui item secondary");
  var i;

  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function () {
      this.classList.toggle("active");
      var dropdownContent = this.nextElementSibling;
      if (dropdownContent.style.display === "block") {
        dropdownContent.style.display = "none";
      } else {
        dropdownContent.style.display = "block";
      }
    });
  }
  if (screen.width <= 699) {
    document.getElementById("content-desktop");
  }
</script>
{% endblock %}

dustpath/templates/base/footer.html
<div class="ui inverted vertical footer segment" style="margin-top: auto;">
  <div class="ui center aligned container">
    <div class="ui stackable inverted divided grid">
      <div class="six wide column">
        <div class="ui inverted link list">
          <img src="{{ url_for('static', filename='images/icon.png') }}" class="ui centered tiny image">
          <br>
          </a>
          ทางของฝุ่น<br> ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5
        </div>
      </div>
      <div class="five wide column">
        <div class="ui inverted link list">
          <br>
          ผู้จัดทำ<br> 1. นายพงศธร ชดช้อย<br> 2. นายธีรยุทธ นุชผดุง<br>
          </a>
          <br>
          ที่ปรึกษาโครงการ<br> ดร. ธนาธิป ลิ่มนา
        </div>
      </div>
      <div class="five wide column">
        <div class="ui inverted link list">
          <br>
          <img src="{{ url_for('static', filename='images/CoE-BG_1_.png') }}" class="ui centered tiny image">
          <a href="http://www.coe.psu.ac.th" class="item">
            <br>
            สาขาวิชาวิศวกรรมคอมพิวเตอร์<br>
            คณะวิศวกรรมศาสตร์
            มหาวิทยาลัยสงขลานครินทร์<br>
            <br>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

dustpath/templates/base/navbar.html
<div class="ui left demo vertical inverted sidebar labeled icon menu">
  <a class="item">
    <i class="home icon"></i>
    หน้าหลัก
  </a>
  <a href="{{ url_for('maps.index') }}" class="item" target="_blank">
    <i class="map icon"></i>
    แผนที่
  </a>
  <a href="{{ url_for('users.record') }}" class="item">
    <i class="user icon"></i>
    โปรไฟล์
  </a>
  <a href="{{ url_for('maps.record') }}" class="item">
      บันทึกแมพ
  </a>
</div>

dustpath/templates/compile/index.html
{% extends "base/default-page.html" %}
{% block content %}
<style>
  .center {
    text-align: center;
  }

  .header1 {
    height: 80vh;
    background: linear-gradient(rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)), url("static/images/dustpath_main_bg.png") center top no-repeat;
    background-size: cover;
    margin-bottom: -28px;
  }

  .title {
    color: white;
    padding-top: calc(30vh - 25px);
  }

  .title h1 {
    font-size: 4.5em;
  }

  .title h3 {
    font-size: 1.5em;
  }

  .main {
    margin-bottom: 50px;
  }

  .main p {
    font-size: 1.2em;
  }

  .main h3 {
    font-size: 1.5em;
  }

  * {
    box-sizing: border-box;
  }

  body {
    font-family: Verdana, sans-serif;
  }

  .mySlides {
    display: none;
  }

  img {
    vertical-align: middle;
  }

  /* Slideshow container */
  .dot {
    height: 15px;
    width: 15px;
    margin: 0 2px;
    background-color: #bbb;
    border-radius: 50%;
    display: inline-block;
    transition: background-color 0.6s ease;
  }

  .active {
    background-color: #717171;
  }

  /* Fading animation */

  @-webkit-keyframes fade {
    from {
      opacity: .4
    }

    to {
      opacity: 1
    }
  }

  @keyframes fade {
    from {
      opacity: .4
    }

    to {
      opacity: 1
    }
  }

  .ui.color1 {
    background-color: #EA7171;
    color: #fff;
  }

  .ui.color2 {
    background-color: #003083;
    color: #fff;
  }

  .ui.color3 {
    background-color: #ffb554;
    color: #fff;
  }

  .ui.color4 {
    background-color: #8DB600;
    color: #fff;
  }

  .ui.color5 {
    background-color: #23c6c8;
    color: #fff;
  }

  .ui.color6 {
    background-color: #ae0001;
    color: #fff;
  }

  /* On smaller screens, decrease text size */
</style>

<div class="header1">
  <div class="title center">
    <h1>ยินดีต้อนรับสู่ ทางของฝุ่น</h1>
    <h3>Welcome to Dustpath Application</h3>
    <h3>ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5</h3>
  </div>
</div>


<div class="ui one column centered grid ">

 
  <a class="ui color5 icon top right pointing big button" {# href="{{url_for('accounts.login')}}" #}>
    <i class="sign in alternate icon"></i>
    <span class="text">เข้าสู่หน้าหลัก</span>
  </a>
</div>

<!-- BUTTON-->
<div class="ui centered grid">
  <div class="column">



  </div>
</div>
<!-- END-->


</div>
</div>
</div>
<script>
  var slideIndex = 0;
  showSlides();

  function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) { slideIndex = 1 }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
  }
</script>
<script>
  $("input:text").click(function () {
    $(this).parent().find("input:file").click();
  });

  $('input:file', '.ui.action.input')
    .on('change', function (e) {
      var name = e.target.files[0].name;
      $('input:text', $(e.target).parent()).val(name);
    });

</script>


{% endblock %}

dustpath/templates/login/login.html
<html>
  <head>
    <title>Flask Intro - login page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="static/bootstrap.min.css" rel="stylesheet" media="screen">
  </head>
  <body>
    <div class="container">
      <h1>Please login</h1>
      <br>
      <form action="" method="post">
        <input type="text" placeholder="Username" name="username" value="{{
          request.form.username }}">
         <input type="password" placeholder="Password" name="password" value="{{
          request.form.password }}">
        <input class="btn btn-default" type="submit" value="Login">
      </form>
      {% if error %}
        <p class="error"><strong>Error:</strong> {{ error }}
      {% endif %}
    </div>
  </body>
</html>

dustpath/templates/main/index.html
{% extends "base/default-page.html" %}
{% block content %}
<style>
  .center {
    text-align: center;
  }

  .header1 {
    height: 80vh;
    background: linear-gradient(rgba(0, 0, 0, 0.5),
        rgba(0, 0, 0, 0.5)), url("static/images/dustpath_main_bg.png") center top no-repeat;
    background-size: cover;
    margin-bottom: -28px;
  }

  .title {
    color: white;
    padding-top: calc(30vh - 25px);
  }

  .title h1 {
    font-size: 4.5em;
  }

  .title h3 {
    font-size: 1.5em;
  }

  .main {
    margin-bottom: 50px;
  }

  .main p {
    font-size: 1.2em;
  }

  .main h3 {
    font-size: 1.5em;
  }

  * {
    box-sizing: border-box;
  }

  body {
    font-family: Verdana, sans-serif;
  }

  .mySlides {
    display: none;
  }

  img {
    vertical-align: middle;
  }

  /* Slideshow container */
  .dot {
    height: 15px;
    width: 15px;
    margin: 0 2px;
    background-color: #bbb;
    border-radius: 50%;
    display: inline-block;
    transition: background-color 0.6s ease;
  }

  .active {
    background-color: #717171;
  }

  /* Fading animation */

  @-webkit-keyframes fade {
    from {
      opacity: .4
    }

    to {
      opacity: 1
    }
  }

  @keyframes fade {
    from {
      opacity: .4
    }

    to {
      opacity: 1
    }
  }

  .ui.color1 {
    background-color: #EA7171;
    color: #fff;
  }

  .ui.color2 {
    background-color: #003083;
    color: #fff;
  }

  .ui.color3 {
    background-color: #ffb554;
    color: #fff;
  }

  .ui.color4 {
    background-color: #8DB600;
    color: #fff;
  }

  .ui.color5 {
    background-color: #23c6c8;
    color: #fff;
  }

  .ui.color6 {
    background-color: #ae0001;
    color: #fff;
  }

  /* On smaller screens, decrease text size */
</style>

<div class="header1">
  <div class="title center">
    <h1>ยินดีต้อนรับสู่ ทางของฝุ่น</h1>
    <h3>Welcome to Dustpath Application</h3>
    <h3>ระบบจำลองการเคลื่อนตัวของฝุ่น PM 2.5</h3>
  </div>
</div>


<div class="ui one column centered grid ">

 
  <a class="ui color5 icon top right pointing big button" {# href="{{url_for('accounts.login')}}" #}>
    <i class="sign in alternate icon"></i>
    <span class="text">เข้าสู่หน้าหลัก</span>
  </a>
</div>

<!-- BUTTON-->
<div class="ui centered grid">
  <div class="column">



  </div>
</div>
<!-- END-->


</div>
</div>
</div>
<script>
  var slideIndex = 0;
  showSlides();

  function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) { slideIndex = 1 }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
  }
</script>
<script>
  $("input:text").click(function () {
    $(this).parent().find("input:file").click();
  });

  $('input:file', '.ui.action.input')
    .on('change', function (e) {
      var name = e.target.files[0].name;
      $('input:text', $(e.target).parent()).val(name);
    });

</script>


{% endblock %}

dustpath/templates/maps/index.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="pusher">
  <div class="ui vertical masthead segment" style="background-color: rgba(242,245,245,0.8)">
    <div class="ui container">
      <div class="ui teal segment" style="margin-top:7%;margin-bottom:100%;">
        <h1>
          Maps ทั้งหมด
        </h1>
        <div class="ui divider">
        </div>
        <div class="ui bottom attached tab segment active" data-tab="first">
          <div class="ui">
            <table id="mytable" class="ui teal celled table">
              <thead>
                <tr>
                  <th>Center[Lat, Long]</th>
                  <th>Radius</th>
                  <th>xx</th>
                </tr>
              </thead>
              <tbody>
                {% for map in maps %}
                <tr>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" id="namelist" style="color: black;">
                        {{ map.center[0] }} {{map.center[1]}}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content"  style="color: black;">
                        {{ map.radius }}
                      </a>
                    </div>
                  </td>
                  <td>
                    <div class="left floated left aligned two wide column">
                      <a class="right aligned content" href="{{ url_for('maps.record') }}">
                        Show
                      </a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

dustpath/templates/maps/record.html
{% extends '/base/base-map.html' %}
{% block body %}
<div class="ui vertical masthead segment" style="background-color: cornsilk;width: 100%; height: 100%;">
    <div id="mapid" style="z-index:1;"></div>
    <div align="right" style="margin-top:2em;z-index: 2;position: absolute;
                              top: 100px;right: 10px;;padding: 5px">
        <button id="record" class="ui teal button" style="margin-top:5px">
            บันทึก</button>
    </div>
</div>

<script type="text/python">
from browser import document, window, ajax
import javascript as js
import datetime
import json


# Access the leaflet.js API
leaflet = window.L

openstreet = leaflet.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    "maxZoom": 19,
	"attribution": '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
})

center = {{center}}
zoom = {{zoom}}
map = leaflet.map('mapid', {
    'center': center,
    'zoom': zoom,
    'layers': openstreet
})
drawnItems = leaflet.FeatureGroup.new()
map.addLayer(drawnItems)
drawControl = leaflet.Control.Draw.new({
         'edit': {
             'featureGroup': drawnItems
         }
})

map.addControl(drawControl)

#จำเป็นต้องใช้กรุ๊ปเพราะจำเป็นต้องใช้ต่อและไม่สามารถอ้างอิงก่อนจะ assign ภายในฟังก์ชันได้
circle_layers = leaflet.layerGroup([])

def save_data(e):
    layers = circle_layers.getLayers()
    if layers:
        layer = layers[0]
        latlng = layer.getLatLng()
        layer_center = [latlng.lat, latlng.lng]
        layer_radius = layer.getRadius()
        
        req = ajax.ajax()
        req.open('POST', '/maps/record', True)
        req.set_header('content-type', 'application/json')
        data = json.dumps(
            {'center': layer_center,
            'radius': layer_radius}
        )
        req.send(data)
        print("data was saved")

def create_circle(e):
    if e.layerType == 'circle':
        layer = e.layer
        latlng = layer.getLatLng()
        layer_center = [latlng.lat, latlng.lng]
        layer_radius = layer.getRadius()
        circle_layer = leaflet.circle(layer_center, {'radius': layer_radius})
        circle_layers.clearLayers()
        circle_layers.addLayer(circle_layer)
        circle_layers.addTo(map)
        
map.on('draw:created', create_circle)
document["record"].bind("click", save_data)

</script>
{% endblock %}

dustpath/templates/result/listresult.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="pusher">
  <div class="ui vertical masthead segment" style="background-color: rgba(242,245,245,0.8)">
    <div class="ui container">
      <div class="ui teal segment" style="margin-top:7%;margin-bottom:100%;">
        <h1>
          ผลลัพธ์ทั้งหมด
        </h1>
        
          <ul>
            {% for file in files %}
              <li><a href="{{url_for('maps.result', filename = file )}}">{{ file }}</a></li>
            {% endfor %}
          </ul>
      </div>
    </div>
  </div>
</div>

<script type="text/python">
from browser import document, window, ajax
import javascript as js
import json
import datetime

def get_name(e):
  namefile = file
  req = ajax.ajax()
  req.open('POST', '/maps/result', True)
  req.set_header('content-type', 'application/json')
  data = json.dumps(
      {'name': namefile}
  )
  req.send(data)

document["getname"].bind("click", get_name)
</script>

{% endblock %} -->

dustpath/templates/result/result.html
{% extends "base/default-page.html" %}
{% block content %}
<div class="pusher">
  <div class="ui vertical masthead segment" style="background-color: rgba(242,245,245,0.8)">
      <img src="{{ url_for('static', filename='gif/' + name)}}">
  </div>
</div>

{% endblock %} -->

dustpath/templates/users/parameter.html
{% extends "base/default-page.html" %}
{% block content %}

<body>
  <h3> Select a date range </h3>
  <form action="" method='POST' name="myform">
      {{ form.csrt_token }}
      {{ form.startdate.label }} {{form.startdate(class='datepicker')}} {{form.hidden_tag()}}
      {{ form.enddate.label }} {{form.enddate(class='datepicker')}} {{form.hidden_tag()}}
      <p>
      {{form.submit()}}
      </p>
  </form>
  </body>   
{% endblock %}

dustpath/templates/users/profile.html
{% extends "base/default-page.html" %}
{% block content %}

<div class="ui vertical masthead segment" style="background-color:rgba(242,245,245,0.8)">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1>
          <h1 style="color: rgb(0, 0, 0);left: 50%;">
            ข้อมูล
            <span style="color: red;">
              {{ user.firstname }}
              {{ user.lastname }}
            </span>
          </h1>
        </h1>
      </div>
    </div>
  </div>
</div>    
{% endblock %}

dustpath/templates/users/record.html
{% extends "base/default-page.html" %}
{% block content %}

<div class="ui vertical masthead segment" style="background-color:rgba(242,245,245,0.8)">
  <div class="ui padding-left aligned container" style="margin-bottom: 1%;">
    <div class="ui teal clearing segment" style="margin-top: 7%;margin-bottom:25%;">
      <div class="ui left aligned container" style="margin-bottom: 1%;">
        <h1>
          <h1 style="color: rgb(0, 0, 0);left: 50%;">
            ข้อมูล
            <form class="ui form" action='' method="POST" style="width: 90%; left:5% ;" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <h1>
                  แก้ไขข้อมูล
                </h1>
                <div class="ui divider"></div>
                <div class="field">
                  <h3 class="ui header">ข้อมูลส่วนตัว</h3>
                </div>
                <div class="two fields">
                  <div class="field">
                    {{ form.firstname.label }}
                    {{ form.firstname }}
                    {% for error in form.lastname.errors %}
                    <p style="color: red;">* โปรดใส่</p>
                    {% endfor %}
                  </div>
                  <div class="field">
                    {{ form.lastname.label }}
                    {{ form.lastname }}
                    {% for error in form.lastname.errors %}
                    <p style="color: red;">* โปรดใส่</p>
                    {% endfor %}
                  </div>
                </div>
                <a href="{{ url_for('users.record')}}" target="_blank">
                  <button class="ui teal button" type="submit" style="right: 0%;">
                    <div class="visible content">ยืนยัน</div>
                  </button>
                </a>
            </form>
          </h1>
        </h1>
      </div>
    </div>
  </div>
</div>    
{% endblock %}